### ISSUE TITLE
Environment Configuration Issue

### ISSUE THREAD

**Issue by lzz19980125** [bschnitzler/dabry#27]
I encountered the following error when running the command:

`python -m dabry.display "movor (scaled)"`

Error log:

D:\miniconda\envs\dabry\lib\site-packages\pyproj\__init__.py:95: UserWarning: pyproj unable to set database path.
  _pyproj_global_context_initialize()
Traceback (most recent call last):
  File "D:\miniconda\envs\dabry\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\miniconda\envs\dabry\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\lizi2\desktop\dabry-main\dabry\display\__main__.py", line 4, in <module>
    from dabry.display.display import Display
  File "c:\users\lizi2\desktop\dabry-main\dabry\display\display.py", line 22, in <module>
    from dabry.flowfield import DiscreteFF
  File "c:\users\lizi2\desktop\dabry-main\dabry\flowfield.py", line 178, in <module>
    class DiscreteFF(FlowField):
  File "c:\users\lizi2\desktop\dabry-main\dabry\flowfield.py", line 312, in DiscreteFF
    def from_cds(cls, grid_bounds: ndarray, t_start: Union[float | datetime], t_end: Union[float | datetime],
TypeError: unsupported operand type(s) for |: 'type' and 'type'

According to GitHub Copilot, this issue arises because the Union type in Python does not support the | operator in my current setup. I have tried Python versions 3.7, 3.8, and 3.9, but all resulted in the same error.

Could you please share the exact environment configuration required to successfully run dabry.display?

**Comment by poine** [comment]
Hello world

I checked today and can confirm that the current code is working on a fresh
Ubuntu 24.04 (python3.12). Sadly, I won't be able to help you with
microsoft windows issues as I don't have access to this closed source
software.

After following the install procedure outlined in
https://github.com/dabry-route (that is, cloning the repository and
pip-installing dependencies in a python virtualenv) , I ran the following
commands:

python3 -m dabry case moving_vortex

python3 -m dabry.display "moving_vortex (scaled)"

They both ran error-free.

Best Regards,

Poine

**Comment by lzz19980125** [comment]
Hi Poine,

Thank you for your kind response. I have successfully configured the environment on Windows, and dabry is now running smoothly.

I have verified that the following environment configuration works:

python==3.10.16
numpy==1.26.4
h5py==3.12.1
plotly==5.24.1
pygrib==2.1.6
scipy==1.14.1
tqdm==4.67.1
easygui==0.98.3
matplotlib==3.8.4
basemap==1.4.1

Thanks again for your assistance!
